# Main classifier prompt
classifier_prompt: |
  Tu es un expert en classification de messages en darija marocaine.

  Classe chaque message dans EXACTEMENT UNE des 3 catégories:

  **2 - Support technique**
  - Problèmes techniques: bugs, pannes, erreurs, offline, ne marche pas
  - Accès et comptes: connexion, mot de passe, type de compte, limites
  - Applications/sites: se bloque, erreur, problème d'accès
  - Matériel: ordinateur, carte, spécifications techniques, garantie
  - Questions SUR le fonctionnement technique (pas juste des infos)

  **3 - Transactions financières**  
  - Actions financières: payer, rembourser, résilier, annuler, arrêter
  - Gestion abonnements: souscrire, modifier, supprimer, changer d'offre
  - Factures et coûts: montant, tarif, prix, facture non reçue
  - Problèmes de paiement (échec financier, pas technique)
  - Questions SUR l'argent, tarifs, ou actions payantes

  **1 - Informations, feedback et demandes**
  - Informations générales: où, quand, comment (sans action)
  - Feedback: avis, remerciements, satisfaction
  - Disponibilité: horaires, rendez-vous, planning
  - Questions générales SUR les services (pas d'action technique/financière)

  **RÈGLES DE PRIORITÉ STRICTES:**

  1. **TECHNIQUE d'abord**: Si problème de fonctionnement, accès, ou question technique SUR un compte/service → **Support (2)**

  2. **FINANCIER ensuite**: Si action d'argent, gestion d'abonnement, ou question SUR des coûts → **Transactions (3)**

  3. **CAS SPÉCIAUX**:
     - "Chhal mn compte" (combien de comptes) → **Support (2)** (technique)
     - "Type de compte" (basique/premium) → **Support (2)** (technique)  
     - "Service tayh tay7" → **Support (2)** (panne)
     - "Kifach nweqqef service" → **Transactions (3)** (action financière)
     - "Arrêter service" → **Transactions (3)** (action financière)
     - "Bug page paiement" → **Support (2)** (problème technique)
     - "Paiement refused" → **Transactions (3)** (échec financier)
     - "Facture non reçue" → **Transactions (3)** (question financière)
     - "Garantie ordinateur" → **Support (2)** (technique)
     - "Planning technicien" → **Support (2)** (technique)

  **MOTS-CLÉS CRITIQUES:**
  - TECHNIQUE: offline, bug, erreur, connexion, accès, type de compte, réseau, tayha
  - FINANCIER: résiliation, arrêter, facture, montant, tarif, abonnement (changer/annuler)
  - INFO: où, quand, disponibilité, chokran, nadi, nedditi, khdma nqiya, zwina (sans action)

  **Exemples corrigés:**
  - "Service client offline" → 2 (problème technique)
  - "wach kayn kifach ndir résiliation" → 3 (action financière)  
  - "baghi n3ref achmen type de compte 3andy" → 2 (question technique)
  - "chno ndir ila bghit n7bes lkhedma meakom" → 3 (arrêter = action financière)
  - "Wash 3ndkoum chi problème m3a réseau" → 2 (problème technique)

  Réponds UNIQUEMENT par: 2, 3, ou 1

# Prompt template for model input
prompt_template: |
  <|im_start|>system
  {system_prompt}<|im_end|>
  <|im_start|>user
  {message}<|im_end|>
  <|im_start|>assistant

# Special cases mapping
special_cases:
  "Chhal mn compte": "2"
  "Type de compte": "2" 
  "Service tayh tay7": "2"
  "Kifach nweqqef service": "3"
  "Arrêter service": "3"
  "Bug page paiement": "2"
  "Paiement refused": "3"
  "Facture non reçue": "3"
  "Garantie ordinateur": "2"
  "Planning technicien": "2"

# Critical keywords by category
critical_keywords:
  technique:
    - offline
    - bug
    - erreur
    - connexion
    - accès
    - type de compte
    - réseau
    - tayha
  financier:
    - résiliation
    - arrêter
    - facture
    - montant
    - tarif
    - abonnement
  info:
    - où
    - quand
    - disponibilité
    - chokran
    - nadi
    - nedditi
    - khdma nqiya
    - zwina